import Vue from 'vue'
import { Button, Menu, Submenu, MenuItem, MenuItemGroup, Input, Form, FormItem, Row, Col , Table, TableColumn, Pagination, Card, Dialog, Breadcrumb, BreadcrumbItem,Message, Loading} from 'element-ui'

Vue.use(Button)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(Input)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Row)
Vue.use(Col)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Pagination)
Vue.use(Card)
Vue.use(Dialog)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Message)
Vue.use(Loading)